<script setup>
import { ref } from "vue"
import headingIcon from "../assets/images/invite/icon/icon-black.png"
import backgroundGold from "../assets/images/shop/question/qa-bg03.png"
import backgroundWhite from "../assets/images/shop/question/qa-bg01.png"
import backgroundRing from "../assets/images/shop/question/qa-bg02.png"
const openFaq = ref(0)
const faqs = [["本館提供哪些付款方式？","提供三種付款方式：信用卡、宅配貨到付款及銀行轉帳。"],["如何查詢訂單處理進度？","登入後進入會員中心，點選訂單查詢，即可查看訂單目前的狀態、付款與出貨資訊。"],["訂單成立後可以取消或修改嗎？","訂單成立後如需取消、加訂或修改數量與尺寸，請先取消原訂單並重新下單。"],["訂購後多久可以收到商品？","完成訂購與付款後，宅配約 1 至 3 個工作天送達，不含例假日。"]]
</script>
<template><main class="shop-faq-page question-page"><img class="question-deco white-top" :src="backgroundWhite" alt=""><img class="question-deco white-bottom" :src="backgroundWhite" alt=""><img class="question-deco gold-top" :src="backgroundGold" alt=""><img class="question-deco ring" :src="backgroundRing" alt=""><img class="question-deco gold-right" :src="backgroundGold" alt=""><div class="question-layout"><section class="question-intro"><h1><img :src="headingIcon" alt="">常見問題</h1></section><section class="faq-panel"><ol><li v-for="([question,answer],index) in faqs" :key="question"><button :aria-expanded="openFaq===index" @click="openFaq=openFaq===index?-1:index"><span>{{question}}</span><i></i></button><div :class="{open:openFaq===index}"><p>{{answer}}</p></div></li></ol></section></div></main></template>
<style scoped>
.question-page{position:relative;isolation:isolate;min-height:820px;overflow:hidden;padding:151px 0 0;background:#c3e7eb}.question-layout{position:relative;z-index:1;display:grid;grid-template-columns:minmax(250px,1fr) minmax(0,570px) minmax(130px,1fr);gap:26px;width:min(calc(100% - 144px),1460px);min-height:731px;margin:auto}.question-intro h1{display:flex;align-items:center;gap:15px;margin:10px 0 0;color:#202020;font-size:clamp(1.3rem,2vw,2rem);font-weight:900;line-height:1;white-space:nowrap}.question-intro h1 img{width:38px;height:32px}.faq-panel{grid-column:2;align-self:start;margin-top:112px}.faq-panel ol{margin:0;padding:0;list-style:none}.faq-panel li{border-bottom:2px solid #222}.faq-panel button{display:grid;grid-template-columns:1fr 34px;align-items:center;gap:20px;width:100%;min-height:61px;padding:0;border:0;background:transparent;color:#222;font-size:clamp(1.1rem,1.5vw,1.45rem);font-weight:700;text-align:left;cursor:pointer;transition:color .2s}.faq-panel button:hover{color:#246f77}.faq-panel i{position:relative;width:24px;height:24px}.faq-panel i::before,.faq-panel i::after{position:absolute;top:50%;left:50%;width:100%;height:2px;background:currentColor;content:"";transform:translate(-50%,-50%)}.faq-panel i::after{transform:translate(-50%,-50%) rotate(90deg)}.faq-panel button[aria-expanded=true] i::after{opacity:0}.faq-panel li>div{display:grid;grid-template-rows:0fr;opacity:0;transition:grid-template-rows .28s,opacity .22s}.faq-panel li>div.open{grid-template-rows:1fr;opacity:1}.faq-panel li>div p{min-height:0;margin:0;padding:10px 25px 24px 0;overflow:hidden;font-size:clamp(1rem,1.2vw,1.12rem);line-height:1.75}.question-deco{position:absolute;z-index:0;pointer-events:none}.white-top{top:-520px;right:-310px;width:min(76vw,1180px);transform:rotate(-8deg)}.white-bottom{bottom:-500px;left:-270px;width:min(76vw,1080px);transform:rotate(8deg)}.gold-top{top:296px;left:13%;width:170px;opacity:.72}.ring{bottom:28px;left:4.5%;width:180px;opacity:.72}.gold-right{right:16%;bottom:105px;width:195px;opacity:.72;transform:rotate(16deg)}:global(body:has(.question-page) .site-header){position:absolute;top:0;right:0;left:0;z-index:100}:global(body:has(.question-page) .site-footer){border-top:0!important}@media(max-width:800px){.question-page{min-height:720px;padding:125px 0 0}.question-layout{display:block;min-height:595px;width:calc(100% - 40px)}.question-intro h1{margin:0;font-size:1.3rem}.question-intro h1 img{width:31px;height:26px}.faq-panel{margin-top:68px}.faq-panel button{grid-template-columns:1fr 30px;min-height:60px;font-size:1.08rem}.faq-panel li>div p{padding-right:18px;font-size:.98rem}.white-top{top:-345px;right:-410px;width:720px}.white-bottom{bottom:-250px;left:-250px;width:680px}.gold-top{top:230px;left:6%;width:110px}.ring{bottom:18px;left:6%;width:115px}.gold-right{right:5%;bottom:110px;width:120px}}
</style>
